In [ ]:
import pandas as pd

## Load agent name

In [27]:
# How to read_csv from google sheet https://medium.com/@Bwhiz/step-by-step-guide-importing-google-sheets-data-into-pandas-ae2df899257f
sheet_name = 'Agent' # replace with your own sheet name
sheet_id = '1QXAKFfXR8oBMXL_mVJx3SkqEpN0qIRG5davdcwCq1-0' # replace with your sheet's ID
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

agent_list = pd.read_csv(url)
agent_list.head()

  prefix_name          agent name  Unnamed: 2
0    property  Nut Ananganjanagit         NaN
1       asset          eakapong_r         NaN
2       condo     Pluto_Landmarks         NaN
3      estate       MaxTierRealty         NaN
4        prop               suwit         NaN

In [28]:
agent_name_list = agent_list['agent name'].dropna().str.lower().tolist()
prefix_name = agent_list['prefix_name'].dropna().str.lower().tolist()

In [29]:
print(len(agent_name_list))
print(len(prefix_name))

124
27

## Load facebook_posts.csv

In [31]:
fb_posts = pd.read_csv("./csv_files/facebook_posts.csv")
fb_posts.head()

,Unnamed: 0,author,content,post_link,post_id
0,0,Pongpun Jukkaew,ลุมพินี พหล 32 ห้องใหม่ จองด่วนครับ!!!… See ...,https://www.facebook.com/groups/13961451675220...,«R2kbddaulqlaleillkqismipapd5aqH1» «R2kbddaulq...
1,1,Jenroob N. Siritharathikun,NaN,https://www.facebook.com/groups/13961451675220...,«r4l» «r4m» «r4n» «r4p» «r4o»
2,2,กัญฑมาศ หิมะเซ็น,NaN,https://www.facebook.com/groups/13961451675220...,«r6b» «r6c» «r6d» «r6f» «r6e»
3,3,อรรถพร พรหมเจริญ,ให้เช่าคอนโด \nThe Selected Kaset-Ngamwongwan\...,https://www.facebook.com/groups/13961451675220...,«r7b» «r7c» «r7d» «r7f» «r7e»
4,4,Arnut Kritsanakan,ปล่อยเช่า Chewathai เกษตร-นวมินทร์\nขนาด 25 ต...,https://www.facebook.com/groups/13961451675220...,«r81» «r82» «r83» «r85» «r84»

In [33]:
fb_posts['author'].value_counts()

author
Unknown                            4
Freedom Seller                     4
Arnut Kritsanakan                  2
Orawan Boonlap                     2
Ann Issaraphon                     2
อรรถพร พรหมเจริญ                   1
Jittraporn Poolinlai               1
Akkaradet Sukasam                  1
เอฟ. มี่                           1
เหมียว มันนี่                      1
Jenroob N. Siritharathikun         1
Arm Teerawat                       1
Paramet Ruengsuwan                 1
Nattapon Pong                      1
น้องนิค กวน กวน นิดหน่อย           1
Nutty Nutty                        1
Thitirat JaAe                      1
Wichayapa Puttharattanawatthana    1
กัญฑมาศ หิมะเซ็น                   1
Jame Ratchanon                     1
Pongpun Jukkaew                    1
Name: count, dtype: int64