In [2]:
import os
import re
import time
import requests
import datetime
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import pandas as pd
import numpy as np

In [3]:
# How to read_csv from google sheet https://medium.com/@Bwhiz/step-by-step-guide-importing-google-sheets-data-into-pandas-ae2df899257f
sheet_name = 'Agent' # replace with your own sheet name
sheet_id = '1QXAKFfXR8oBMXL_mVJx3SkqEpN0qIRG5davdcwCq1-0' # replace with your sheet's ID
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

agent_list = pd.read_csv(url)
agent_list.head()

  prefix_name          agent name  Unnamed: 2
0    property  Nut Ananganjanagit         NaN
1       asset          eakapong_r         NaN
2       condo     Pluto_Landmarks         NaN
3      estate       MaxTierRealty         NaN
4        prop               suwit         NaN

In [ ]:
def is_agent(fullname: str, prefixes: list) -> bool:
    normalized_fullname = fullname.replace(" ", "").lower()
    return any(prefix.replace(" ", "").lower() in normalized_fullname for prefix in prefixes)

In [347]:
def extract_numbers(text: str) -> str:
    """Extracts numbers from text while keeping hyphens and dot."""
    return "".join(re.findall(r"[-\d.]+", text))

In [348]:
agent_name_list = agent_list['agent name'].dropna().str.lower().tolist()
prefix_name = agent_list['prefix_name'].dropna().str.lower().tolist()

In [349]:
room_dict = {
    "date": [],
    "condo_name":[],
    "building": [],
    "floor": [],
    "area": [],
    "bedroom": [],
    "bathroom": [],
    "price": [],
    "phone": [],
    "owner": [],
    "room_number": [],
    "line_id": [],
    "url": []
}

In [350]:
page_urls = ["https://www.livinginsider.com/searchword/Condo/Rent/1/%E0%B8%A3%E0%B8%B1%E0%B8%87%E0%B8%AA%E0%B8%B4%E0%B8%95.html",
            ]

In [352]:
def search_room(url):    
    i = 0
    while True:

        page_content = requests.get(url)
        soup = BeautifulSoup(page_content.content, 'html.parser')
        posts = soup.find_all('div', class_="col-md-3 col-sm-4 col-xs-6 padding_topic margin_top_topic")
        # print(len(posts))
        for post in posts:

            link = post.find('a', class_="image-ratio-4-3").get('href')
            in_post_content = requests.get(link)
            in_post_soup = BeautifulSoup(in_post_content.content, 'html.parser')
            detail_content = in_post_soup.find('div', class_="detail-content col-sm-12 main-detail-content")
            owner = detail_content.find('label').text
            if owner.lower() in agent_name_list or is_agent(owner, prefix_name):
                print(f"Owner : {owner} continue")
                continue
            condo_name = detail_content.find('span', class_="text_project_detail_green").text
            price = detail_content.find('div', class_="t-24 price-detail mt-0 price_topic").text.replace('\n', '')
            
            detail_property = detail_content.find('div', class_="row detail-row")
            room_details = detail_property.find_all('span', class_="detail-property-list-text")
            properties = []
            for detail in room_details:
                room_detail = detail.text
                room_detail = re.sub(r'[\s\n]', '', room_detail)
                properties.append(room_detail)

            room_dict['date'].append(datetime.datetime.now().strftime("%d/%m/%Y"))
            room_dict['condo_name'].append(condo_name)
            room_dict['building'].append(None)
            room_dict['floor'].append(extract_numbers(properties[1]))
            room_dict['area'].append(extract_numbers(properties[0]))
            room_dict['bedroom'].append(extract_numbers(properties[2]))
            room_dict['bathroom'].append(extract_numbers(properties[3]))
            room_dict['price'].append(extract_numbers(price))
            room_dict['phone'].append(None)
            room_dict['owner'].append(owner)
            room_dict['room_number'].append(None)
            room_dict['line_id'].append(None)
            room_dict['url'].append(link)

        pagination = soup.find('ul', class_="pagination")
        pages = pagination.find_all('a', class_="loading_page")
        next_page = pages[-1]
        print(next_page.text)
        if next_page.text != " Next ›" or i == 50:
            print("Break!!!")
            break
        else:
            url = next_page.get('href')
            i += 1
            print(f"Finish page :{i}")

In [353]:
for page_url in page_urls:
    search_room(page_url)

Owner : Easyhomeland continue
Owner : NextHome continue
Owner : NextHome continue
Owner : เพื่อนอสังหาฯ... continue
Owner : PaphatAsset continue
Owner : bkkagencyproperty continue
Owner : Fast forrent condo continue
Owner : Unicondo continue
Owner : Differestate continue
Owner : Fast forrent condo continue
Owner : thammarat_pens continue
Owner : Fast forrent condo continue
Owner : rassamee_mnliving continue
Owner : Gowealthasset continue
Owner : matchaprop continue
Owner : บริการโพสต์_อสังหา... continue
Owner : serve1 continue
Owner : serve1 continue
 Next ›
Finish page :1
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : serve1 continue
Owner : qhome2188 continue
Owner : BoatProperty continue
Owner : katnuttakun continue
Owner : nuch.chaba64@gmail.c... continue
Owner : Wealthiness_Estate continue
Owner : Q-home123 continue
Owner : Aofagent continue
Owner : Keng Property continue
Owner : Fast forrent condo continue
Owner : LivingLegacy continue
Owner : Fast forrent condo continue
Owner : Unicondo continue
Owner : peacexplace continue
Owner : Fast forrent condo continue
Owner : WynzonRealEstate continue
Owner : NYLE Property continue
 Next ›
Finish page :2
Owner : Condo BU Rangsit continue
Owner : nuch.chaba64@gmail.c... continue
Owner : knmeritproperty continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Preiw Agency continue
Owner : Preiw Agency continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : BCA Real Estate Agen... continue
Owner : matchaprop continue
Owner : Wealthiness_Estate continue
Owner : Miki Chatbenjarus continue
 Next ›
Finish page :3
Owner : Miki Chatbenjarus continue
Owner : pimwiga continue
Owner : Bangkokcondo_Advisor continue
Owner : ราคาอสังหาฯ continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
 Next ›
Finish page :4
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
 Next ›
Finish page :5
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : Asset A Plus continue
Owner : AgentBank continue
Owner : AgentBank continue
Owner : Easyhomeland continue
Owner : Easyhomeland continue
Owner : Easyhomeland continue
Owner : WinnerAgent continue
Owner : WinnerAgent continue
Owner : Condo.P continue
Owner : bkkrealestate888 continue
Owner : Chicha  mestate continue
Owner : Chicha  mestate continue
Owner : Chicha  mestate continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : Patcha.realestate continue
Owner : Fast forrent condo continue
Owner : Aor condo continue
Owner : geoprop97 continue
Owner : geoprop97 continue
Owner : geoprop97 continue
Owner : geoprop97 continue
Owner : geoprop97 continue
 Next ›
Finish page :6
Owner : geoprop97 continue
Owner : geoprop97 continue
Owner : Wit_Double_S_Condo@h... continue
Owner : Acorestestate continue
Owner : TPE ( Thanespon Esta... continue
Owner : TPE ( Thanespon Esta... continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : qhome2188 continue
Owner : JHR Real Estate continue
Owner : คอนโด_แจ้งวัฒนะ... continue
Owner : nakarin-sari continue
Owner : thanyapornm8k continue
Owner : ราคาอสังหาฯ continue
Owner : pa5158 continue
 Next ›
Finish page :7
Owner : Empathycondo01 continue
Owner : LUCQProperty continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Urban8property continue
Owner : MaxTierRealty continue
Owner : Maithanakit continue
Owner : Miki Chatbenjarus continue
Owner : PP_Property continue
Owner : Miki Chatbenjarus continue
Owner : Fast forrent condo continue
Owner : Maithanakit continue
Owner : New Nirinya continue
 Next ›
Finish page :8
Owner : Prince Property continue
Owner : Prince Property continue
Owner : Prince Property continue
Owner : Prince Property continue
Owner : nuch.chaba64@gmail.c... continue
Owner : bkkagencyproperty continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : PPpropertyy continue
Owner : Cluebkk continue
Owner : PAISIT REAL ESTATE C... continue
Owner : Fast forrent condo continue
Owner : maha.rentcondo continue
Owner : sscondo426 continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : bunnagent continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : PP_Property continue
Owner : HappyRealProperty continue
 Next ›
Finish page :9
Owner : HappyRealProperty continue
Owner : PP_Property continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : BRProperty continue
Owner : TheEnrichByCondonewb continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : Condo.P continue
Owner : deever_property continue
Owner : mayestate continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : All Living continue
Owner : Suprawe continue
Owner : pa5158 continue
Owner : Suprawe continue
Owner : pimwiga continue
Owner : Empathycondo01 continue
Owner : SiriProperty continue
Owner : NatchaProperty continue
Owner : NatchaProperty continue
Owner : NatchaProperty continue
Owner : Glorious Real Estate continue
Owner : estatesynergy continue
Owner : NatchaProperty continue
 Next ›
Finish page :10
Owner : NatchaProperty continue
Owner : Preiw Agency continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : HappyRealProperty continue
Owner : Homepropertyconsulti... continue
Owner : www.baansuayproperty... continue
Owner : Rangrak Estate continue
Owner : บริษัท ดีดี คอนโด แล... continue
Owner : Homepropertyconsulti... continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : Puncondo continue
Owner : HappyRealProperty continue
Owner : Unicondo continue
Owner : serve1 continue
Owner : แคท แมวมอง อสังหา... continue
Owner : แคท แมวมอง อสังหา... continue
Owner : Condo-i continue
Owner : Unicondo continue
Owner : Unicondo continue
Owner : Miki Chatbenjarus continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : www.baansuayproperty... continue
Owner : www.baansuayproperty... continue
Owner : TF_kukkai continue
Owner : Neox Estate continue
 Next ›
Finish page :11
Owner : U. HOME REAL ESTATE continue
Owner : Wasinee88 continue
Owner : CT Property Manageme... continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : TF_kukkai continue
Owner : sscondo426 continue
Owner : Condo.P continue
Owner : Na_wingsprop continue
Owner : Sahakorn continue
Owner : Puncondo continue
Owner : tooncondo continue
Owner : WinnerAgent continue
Owner : Maithanakit continue
Owner : Empathycondo continue
Owner : Correct Property continue
Owner : ERA-Holding-Thailand continue
Owner : JHR Real Estate continue
Owner : JHR Real Estate continue
Owner : JHR Real Estate continue
Owner : Juthamas Pansombut continue
 Next ›
Finish page :12
Owner : PP_Property continue
Owner : JHR Real Estate continue
Owner : JHR Real Estate continue
Owner : JHR Real Estate continue
Owner : Your Estate Thailand continue
Owner : Correct Property continue
Owner : All Living continue
Owner : @Feelgoodhome continue
Owner : PP_Property continue
Owner : PP_Property continue
Owner : Miki Chatbenjarus continue
Owner : WinnerAgent continue
Owner : Cluebkk continue
Owner : นติภา เลากุลรัตน์... continue
Owner : nuch.chaba64@gmail.c... continue
Owner : nuch.chaba64@gmail.c... continue
Owner : CT Property Manageme... continue
Owner : Urban8property continue
Owner : Wproperty4642 continue
Owner : Homepropertyconsulti... continue
Owner : Miki Chatbenjarus continue
 Next ›
Finish page :13
Owner : Nice Rent Real estat... continue
Owner : Kingland Estate Team continue
Owner : Sahakorn continue
Owner : pa5158 continue
Owner : Cluebkk continue
Owner : eakapong_r continue
Owner : seasonspropoty continue
Owner : Glorious Real Estate continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : uptownassets continue
Owner : Homepropertyconsulti... continue
Owner : uptownassets continue
Owner : Condo-i continue
Owner : WinnerAgent continue
Owner : Maithanakit continue
Owner : eakapong_r continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : uptownassets continue
Owner : uptownassets continue
Owner : Miki Chatbenjarus continue
Owner : Miki Chatbenjarus continue
Owner : eakapong_r continue
Owner : InterHome continue
Owner : Miki Chatbenjarus continue
Owner : Kingland Estate Team continue
Owner : SenX Resale continue
Owner : ReadyAsset4289 continue
Owner : ReadyAsset4289 continue
Owner : ReadyAsset4289 continue
 Next ›
Finish page :14
Owner : Easythaihome continue
Owner : Homepropertyconsulti... continue
Owner : Homepropertyconsulti... continue
Owner : SiriProperty continue
Owner : Homepropertyconsulti... continue
Owner : Homepropertyconsulti... continue
Owner : vk9property continue
Owner : Empathycondo01 continue
Owner : ReadyAsset4289 continue
Owner : Condo.P continue
Owner : ReadyAsset4289 continue
Owner : ReadyAsset4289 continue
Owner : ReadyAsset4289 continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Condo.P continue
Owner : Plus Property Co.,Lt... continue
Owner : Plus Property Co.,Lt... continue
Owner : Plus Property Co.,Lt... continue
Owner : Ty TTC Property continue
Owner : Condo.P continue
Owner : DD Asset (thailand) ... continue
‹ Prev
Break!!!

In [ ]:
OWNER_PATH = './csv_files/owner_room.csv'
EXPECTED_AGENT_PATH = './csv_files/expected_agent.csv'
EXPECTED_AGENT_LIST_PATH = './csv_files/expected_agent_list.csv'

all_room_df = pd.DataFrame(room_dict)

# filler owner
filltered_df = all_room_df[all_room_df.groupby('owner')['owner'].transform("count") < 4]

# fillter agent
expected_agent_df = all_room_df[all_room_df.groupby('owner')['owner'].transform("count") >= 4]
expected_agent_list = pd.Series(expected_agent_df['owner'].value_counts())

# export to csv
filltered_df.to_csv(OWNER_PATH)
expected_agent_df.to_csv(EXPECTED_AGENT_PATH)
expected_agent_list.to_csv(EXPECTED_AGENT_LIST_PATH)

In [355]:
filltered_df.groupby("owner").size()

owner
0834292959              1
ARMTRAIPOP              1
Airutdar Pholjun        1
Alisa_Uasaman           2
Apiwit                  3
                       ..
รัตนชาติ...             1
สุดชา ผาผง...           1
เกรดสุรางค์...          1
โอปอชา_ลาลาลันล่า...    3
ให้ทุกวันเป็นกำไร...    1
Length: 144, dtype: int64

In [356]:
expected_agent_df.groupby("owner").size()

owner
Charles-Heng              4
Chayapa                   6
Natchaaa                 15
Tanya_Noi                18
primporn                  5
ณัฏฐนันท์  (คุณสุ)...    12
dtype: int64

In [357]:
expected_agent_df

,date,condo_name,building,floor,area,bedroom,bathroom,price,phone,owner,room_number,line_id,url
1,10/03/2025,เคฟ คอนโด,None,24..,24..,4,1,12000.500...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/472...
11,10/03/2025,ดีคอนโด ไฮป์ รังสิต,None,26..,26..,5-10,1,12000.462...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/253...
16,10/03/2025,เทอร์ร่า เรสซิเดนซ์ เฟส 1 - 2,None,33..,33..,30,1,12000.364...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/239...
17,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,24.60..,24.60..,1,1,14000.569...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
18,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22..,22..,7,1,12000.545...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
19,10/03/2025,นิว ครอส คูคต สเตชัน,None,30.55..,30.55..,5-10,1,11000.360...,None,primporn,None,None,https://www.livinginsider.com/livingdetail/223...
20,10/03/2025,นิว คอร์ คูคต สเตชัน,None,22.25..,22.25..,5-10,1,8500.382...,None,primporn,None,None,https://www.livinginsider.com/livingdetail/240...
21,10/03/2025,นิว คอร์ คูคต สเตชัน,None,46.50..,46.50..,1-4,2,20000.430...,None,primporn,None,None,https://www.livinginsider.com/livingdetail/245...
22,10/03/2025,นิว คอร์ คูคต สเตชัน,None,26.25..,26.25..,1-4,1,9500.362...,None,primporn,None,None,https://www.livinginsider.com/livingdetail/239...
23,10/03/2025,นิว ครอส คูคต สเตชัน,None,26.50..,26.50..,1-4,1,9000.340...,None,primporn,None,None,https://www.livinginsider.com/livingdetail/239...
27,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,23..,23..,8,1,13000.565...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/246...
30,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22.60..,22.60..,2,1,12000.531...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
32,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,22..,22..,5,,4500.205...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/136...
35,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22.60..,22.60..,8,1,11000.487...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
39,10/03/2025,ดิ เอ็กเซล คูคต,None,25..,25..,2,1,6500.260...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/246...
40,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,3,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/251...
46,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,38..,38..,4,2,23000.605...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/239...
55,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,38..,38..,2,2,23000.605...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/239...
56,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,5,1,7500.268...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/254...
57,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,5-10,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/151...
58,10/03/2025,ดิ เอ็กเซล คูคต,None,25..,25..,5-10,1,7000.280...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/112...
59,10/03/2025,ดิ เอ็กเซล คูคต,None,35..,35..,7,1,11000.314...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/179...
62,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,38..,38..,3,2,23000.605...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
63,10/03/2025,นิว คอร์ คูคต สเตชัน,None,22..,22..,6,,9000.409...,None,Charles-Heng,None,None,https://www.livinginsider.com/livingdetail/252...
66,10/03/2025,ดิ เอ็กเซล คูคต,None,25..,25..,7,1,6500.260...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/252...
68,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22.60..,22.60..,8,1,11000.487...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
69,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,6,1,7500.268...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/159...
70,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,5,1,7500.268...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/253...
72,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,24.60..,24.60..,8,1,13000.528...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
81,10/03/2025,นิว คอร์ คูคต สเตชัน,None,26..,26..,6,1,11000.423...,None,Charles-Heng,None,None,https://www.livinginsider.com/livingdetail/252...
94,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22.60..,22.60..,3,1,12000.531...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/238...
95,10/03/2025,เสนาคิทท์ รังสิต - ติวานนท์,None,27.05..,27.05..,4,1,7000.259...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/246...
96,10/03/2025,ดิ เอ็กเซล คูคต,None,25.30..,25..,5,1,6500.260...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/203...
100,10/03/2025,เคฟ ทาวน์ ไอส์แลนด์,None,22..,22..,6,1,12000.545...,None,Natchaaa,None,None,https://www.livinginsider.com/livingdetail/214...
109,10/03/2025,เดอะ คิทท์ พลัส พหลโยธิน - คูคต,None,28..,28..,2,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/251...
110,10/03/2025,เดอะ คิทท์ พลัส พหลโยธิน - คูคต,None,28..,28..,3,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/252...
111,10/03/2025,เดอะ คิทท์ พลัส พหลโยธิน - คูคต,None,28..,28..,5-10,1,7500.268...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/169...
112,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,5-10,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/225...
119,10/03/2025,กรีเน่ ดอนเมือง - สรงประภา,None,34..,34..,5,1,10000.294...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/738...
120,10/03/2025,เสนาคิทท์ รังสิต - ติวานนท์,None,28..,28..,1,1,6000.214...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/242...
121,10/03/2025,เดอะคิทท์ รังสิต - ติวานนท์,None,28..,28..,6,1,6500.232...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/103...
122,10/03/2025,เดอะคิทท์ ไลท์ บางกะดี - ติวานนท์,None,28..,28..,5,1,6000.214...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/301...
123,10/03/2025,เดอะคิทท์ รังสิต - ติวานนท์,None,28..,28..,1,1,5500.196...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/204...
124,10/03/2025,เดอะคิทท์ ไลท์ บางกะดี - ติวานนท์,None,28..,28..,4,1,6000.214...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/204...
125,10/03/2025,เสนาคิทท์ รังสิต - ติวานนท์,None,26..,26..,4,1,6500.250...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/248...
137,10/03/2025,เสนาคิทท์ รังสิต - ติวานนท์,None,26.30..,26.30..,4,1,7000.266...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/246...
149,10/03/2025,นิว คอร์ คูคต สเตชัน,None,26..,26..,6,1,11000.423...,None,Charles-Heng,None,None,https://www.livinginsider.com/livingdetail/252...
157,10/03/2025,เดอะ คิทท์ ลำลูกกา คลอง 2,None,28..,28..,3,1,5500.196...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/127...
158,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,7,1,7500.268...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/221...
159,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,4,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/110...
165,10/03/2025,เดอะ คิทท์ พลัส พหลโยธิน - คูคต,None,28..,28..,1-4,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/251...
179,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,22..,22..,5,,4500.205...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/136...
180,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,22..,22..,6,,4500.205...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/144...
181,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,22..,22..,5-10,,5500.250...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/105...
187,10/03/2025,นิว คอร์ คูคต สเตชัน,None,26..,26..,2,1,11000.423...,None,Charles-Heng,None,None,https://www.livinginsider.com/livingdetail/252...
189,10/03/2025,เสนาคิทท์ รังสิต - ติวานนท์,None,26..,26..,4,1,6500.250...,None,ณัฏฐนันท์ (คุณสุ)...,None,None,https://www.livinginsider.com/livingdetail/241...
208,10/03/2025,เคฟ ทาวน์ โคโลนี,None,26..,26..,7,1,12000.462...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/206...
220,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,22..,22..,7,,4500.205...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/144...
221,10/03/2025,ลุมพินี ทาวน์ชิป รังสิต คลอง 1,None,21.50..,21.50..,6,,4500.209...,None,Chayapa,None,None,https://www.livinginsider.com/livingdetail/325...
226,10/03/2025,ดิ เอ็กเซล คูคต,None,28..,28..,7,1,7000.250...,None,Tanya_Noi,None,None,https://www.livinginsider.com/livingdetail/144...